name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18.17.0
    steps:
      - uses: actions/checkout@v4
      - name: Change ownership of /github/home
        run: chown -R $(whoami) /github/home
      - name: Install node modules
        run: npm install
  unit-test:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: node:18.17.0
    steps:
      - uses: actions/checkout@v4
      - name: Change ownership of /github/home
        run: chown -R $(whoami) /github/home
      - name: Install node modules
        run: npm install
      - name: Run tests with coverage with console and html report
        run: npm test
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '80'
  deploy:
    needs: [build, unit-test]
    runs-on: ubuntu-latest
    env:
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
    steps:
      - name: Deploy by hook
        run: curl -X POST $RENDER_DEPLOY_HOOK > deploy.json
      - uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: deploy.json
      - name: Sleep by two minutes
        run: sleep 120
  acceptance-test:
    needs: [deploy]
    runs-on: ubuntu-latest
    container:
      image: node:18.17.0
    steps:
      - uses: actions/checkout@v4
      - name: Change ownership of /github/home
        run: chown -R $(whoami) /github/home
      - name: Install node modules
        run: npm install
      - name: Run acceptance tests
        run: npm run test:acceptance --HOST=https://node-express-mp7s.onrender.com --PORT=443 --CONTEXT_PATH=/api --AMBIENTE=dev
      - uses: actions/upload-artifact@v4
        with:
          name: cucumber-report.html
          path: cucumber-report.html
  performance-test-artillery:
    needs: [deploy]
    runs-on: ubuntu-latest
    container:
      image: node:18.17.0
    steps:
      - uses: actions/checkout@v4
      - name: Change ownership of /github/home
        run: chown -R $(whoami) /github/home
      - name: Install node modules
        run: npm install
      - name: Create host variable
        run: export HOST="https://node-express-mp7s.onrender.com"
      - name: Create context path variable
        run: export CONTEXT_PATH="/api"
      - name: Create port variable
        run: export PORT="443"
      - name: Create base path variable
        run: export BASE_PATH="$HOST:$PORT$CONTEXT_PATH"
      - name: Run artillery performance tests
        run: npx artillery run -e dev performance-test/artillery/node-express.yml --output artillery-test.json
      - name: Generate artillery performance tests html report
        run: npm run test:performance-report
      - uses: actions/upload-artifact@v4
        with:
          name: artillery-report.html
          path: artillery-report.html
